### ISSUE TITLE
PKG_HAVE_DEFINE_WITH_MODULES not found when run ./autogen.sh

### ISSUE THREAD

**Issue by RocooHash** [lxin/quic#7]
Build Enviorment: Ubuntu 22.04
Linux Kernel Version: Linux jammy 6.5.0-25-generic

I follow the install guide, when i want to Build QUIC Kernel Module and Libquic, and met this issue

```
configure.ac:27: installing './compile'
configure.ac:22: installing './install-sh'
configure.ac:22: installing './missing'
src/tlshd/Makefile.am: installing './depcomp'
configure.ac:61: error: possibly undefined macro: PKG_HAVE_DEFINE_WITH_MODULES
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

**Comment by lxin** [comment]
Interestingly, it works on the ubuntu23 and RHEL distros, probably it's because of the 'autoconf' version.

Anyway, PKG_HAVE_DEFINE_WITH_MODULES is not a common Macro, I've changed it to PKG_CHECK_MODULES() in ktls-utils.

please re-clone https://github.com/lxin/ktls-utils.git and re-build on your env.

Thanks.

**Comment by RocooHash** [comment]
thank u, it works for me
